version: '3'

services:
  db:
    user: $UID
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret_here
      MONGO_INITDB_DATABASE: ecommerce
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret_db
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
